package state

const (
	TS_CREATED = iota + 1
	TS_AMENDMENT_REQUESTED
	TS_AMENDED
	TS_KEBD_REQUESTED
	TS_KEBD_REQUEST_AMENDMENT_REQUEST_SENT
	TS_KEBD_AMENDED
	TS_GUARANTEE_AMOUNT_REQUEST_SENT
	TS_GUARANTEE_AMOUNT_AMEND_REQUEST_SENT
	TS_GUARANTEE_AMOUNT_AMENDED
	TS_BUYER_ACCEPTED
	TS_SELLER_ACCEPTED
	TS_ACCEPTED
	TS_DECLINED
)
